### ISSUE TITLE
Teku does not check for liveness of the TCP connections for metrics

### ISSUE THREAD

**Issue by Neurone** [Consensys/teku#4327]
### Description
Teku does not check TCP connection liveness for metrics.

If a Prometheus client on another machine establish a connection and then it stops sending packets (i.e. due to crash, networking errors, malicious behaviours, etc.), the server-side connection remains `ESTABLISHED` forever. The next time the Prometheus client tries to connect to Teku again, a new connection is created.

I noticed this because of a misconfiguration in the Raspberry I use as monitoring server. Every 20 minutes the Pi tries to suspend, but it fails and it reboot itself. All this takes less then 30 seconds, so it's not really noticeable, but it is enough to cause my Teku an increment of 72 stale TCP connections per day. The only way to force Teku to kill those connections is to restart it.

It's not a fault in machine or network configuration: I have other servers on the same machine along with Teku (i.e. geth) and the same Prometheus client works fine with all of them except Teku.

The problem seems related to how `io.vertx` handles TCP connections, or maybe it is `io.netty`'s fault.

I didn't understand enough how vertx uses netty, but I created a custom build with `netty 4.1.67` and `vertx 3.9.9` (released just few hours ago) and nothing changed.

I tried with `vertx 4.1.3` also, but I encountered other problems so it's not a valid test.

### Steps to Reproduce (Bug)
1. Enable metrics (`--metrics-enabled=true`)
2. Establish a connection from another machine (i.e. with Prometheus, or manually with something like `nc <IP> <PORT>`)
3. Disconnect or forcibly terminate the client machine
4. Connection remains `ESTABLISHED` on the Teku side
5. Connect or start the client machine again
6. Establish a new connection
7. The new connection is created and established, but the old one remains `ESTABLISHED` forever

**Expected behavior:**
If Prometheus client goes offline forcibly or due to unexpected issues, the server-side connection is closed after a timeout.

**Actual behavior:**
If Prometheus client goes offline forcibly or due to unexpected issues, the server-side connection remains open forever. The next time the Prometheus client tries to connect to Teku, a new connection is established.

**Frequency:**
It happens every time I tried. Pretty _solid_ behaviour, maybe is it an intended configuration for some reason?

### Versions
* Software version: `teku/v21.8.2/linux-x86_64/-privatebuild-openjdk64bitservervm-java-14`
* Java version: `openjdk version "14.0.2" 2020-07-14 -- OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04) --
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)`
* OS Name & Version: `Ubuntu 20.04.3 LTS`
* Kernel Version: `Linux ethmachine 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Neurone** [comment]
It seems possible to set a timeout using [setIdleTimeout](https://vertx.io/docs/3.9.9/apidocs/io/vertx/core/http/HttpServerOptions.html#setIdleTimeout-int-) in Vertx's [HttpServerOptions](https://vertx.io/docs/3.9.9/apidocs/io/vertx/core/http/HttpServerOptions.html) class.

It seems to me that Teku uses a library from Besu to create the metrics server, but the Besu [MetricsHttpService](https://github.com/hyperledger/besu/blob/main/metrics/core/src/main/java/org/hyperledger/besu/metrics/prometheus/MetricsHttpService.java) does not currently allow setting the setIdleTimeout parameter.

**Comment by rolfyone** [comment]
Thanks for the write-up. I've put in a besu PR to add an idle timeout, and tested manually with telnet connections, and that should solve the issue.  We'll have to wait until besu releases their next version until we can pull the change through to teku.

**Comment by Neurone** [comment]
I suggested a PR (https://github.com/hyperledger/besu/pull/2752) to make idle timeout configurable
