### ISSUE TITLE
Feature: Liveness endpoint for doppelganger protection interop

### ISSUE THREAD

**Issue by yorickdowne** [Consensys/teku#4453]
### Description

I'd love to see a [liveness endpoint](https://github.com/ethereum/beacon-APIs/pull/131) implemented, at `/eth/v1/validator/liveness`. This would make it possible to use the doppelganger protection in a  Lighthouse validator client with Teku, and thus Infura.

**Comment by rolfyone** [comment]
Some reading / resources:
https://hackmd.io/Szjk_d1gTrWGuUsLojmoqA
https://github.com/sigp/lighthouse/blob/stable/validator_client/src/doppelganger_service.rs

https://github.com/sigp/lighthouse/blob/7c88f582d955537f7ffff9b2c879dcf5bf80ce13/beacon_node/beacon_chain/src/beacon_chain.rs#L3757-L3782

https://github.com/sigp/lighthouse/blob/7c88f582d955537f7ffff9b2c879dcf5bf80ce13/beacon_node/http_api/src/lib.rs#L2139-L2180

I made an attempt at observing liveness based on state, but it's not really as reliable as i'd like. Once we're on Altair it does improve, and but a validator can attest as much as 32 blocks late, so it might be a little dangerous to rely completely on state.

Lighthouse has a working implementation of this, and lots of corner cases etc have been identified, which would help with testing of an overall doppelganger protection solution.
