### ISSUE TITLE
Add Teku to the Hive test infrastructure

### ISSUE THREAD

**Issue by benjaminion** [Consensys/teku#5787]
See https://hivetests2.ethdevops.io/

The specific tests for the Eth2/Consensus clients are [here](https://github.com/txrx-research/TestingTheMerge/tree/main/tests). It's likely that more will be added soon.

**Comment by jimmygchen** [comment]
Hi @benjaminion 

I have created a PR for adding Teku to Hive - be great if you could take a look at this:
https://github.com/ethereum/hive/pull/570.

Thanks!

**Comment by benjaminion** [comment]
@jchen86 That's wonderful! Thank you.

We'll review the PR to double check from our side - might be after the weekend, but will let you know.

**Comment by jimmygchen** [comment]
Hi,

I added a comment on the hive PR. It looks like the test timeout needs to be increased for Teku to proceed further in the simulation tests. At the moment it's failing waiting for finality after startup. More details here:

https://github.com/ethereum/hive/pull/570#issuecomment-1166146182

**Comment by zilm13** [comment]
Thanks to @jchen86 and @marioevz, Teku is finally a part of the Hive, so this task is completed, but I've created separate task #5934 to track successful passing of tests by Teku
