### ISSUE TITLE
`liveness` endpoint not conform to the specification?

### ISSUE THREAD

**Issue by nalepae** [Consensys/teku#7204]
The Beacon API `v2.4.0` defines the [getLiveness endpoint](https://ethereum.github.io/beacon-APIs/#/Validator/getLiveness) as following:

- **Verb:** POST
- **Endpoint:**  `/eth/v1/validator/liveness/{epoch}`
- **Body example:** 
```
["1", "42", "1664"]
```
(List of indexes)

However, the Teku implements the [getLiveness endpoint](https://docs.teku.consensys.net/api#tag/Experimental/operation/postValidatorLiveness) in a slightly different way:
- **Verb:** POST (same)
- **Endpoint:**  `/eth/v1/validator/liveness/{epoch}` (same)
- **Body example:** 
```
{
   "indices": [
      "1",
      "42",
      "1663"
   ]
}
```
(Map with `indices` as key and with a list of indexes as value)

Is there any specific reason not to conform to the specification?
If no, would it be possible to adapt it?
If you don't want do break retro-compatibility, I guess it's possible for the endpoint to accept both current Teku body and ETH beacon API specification body.

**Comment by rolfyone** [comment]
Hey! thanks for raising this, it looks like we've always done it in that way. I'll take a look right away.
